stages:
  - build
  - test

build:
  stage: build
  image: gradle:8.6-jdk21
  script:
    - echo "Building the project..."
    - gradle build
  only:
    - martine14

test:
  stage: test
  image: gradle:8.6-jdk21
  coverage: '/Code coverage: /Total.*?([0-9]{1,3})%/'
  script:
    - echo "Testing the project..."
    #- gradle test
    - gradle test jacocoTestReport
  artifacts:
    paths:
      - build/reports/
  only:
    - martine14
