stages:
  - build
  - test
  - visualize

build:
  stage: build
  image: gradle:8.6-jdk21
  script:
    - echo "Building the project..."
    - gradle build
  only:
    - martine14

test:
  stage: test
  image: gradle:8.6-jdk21
  script:
    - echo "Testing the project..."
    - gradle test jacocoTestReport
  artifacts:
    paths:
      - core/build/reports/jacoco/test/jacocoTestReport.xml
  only:
    - martine14

test-coverage: 
  stage: visualize 
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script: 
    - |
      if [ ! -d "core/build" ]; then
        mkdir -p core/build
      fi
    - python /opt/cover2cover.py core/build/reports/jacoco/test/jacocoTestReport.xml $CI_PROJECT_DIR/core/build > cobertura.xml
  needs: ["test"] 
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts: 
    reports: 
      coverage_report:
        coverage_format: cobertura
        path: core/build/cobertura.xml
  only:
  - martine14
