stages:
  - build
  - test

build:
  stage: build
  image: gradle:8.6-jdk21
  script:
    - echo "Building the project..."
    - gradle build
  only:
    - main

test:
  stage: test
  image: gradle:8.6-jdk21
  script:
    - echo "Testing the project..."
    - gradle test
  only:
    - main
